Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/focal64"
  config.vm.network "private_network", ip: "192.168.100.101"
  config.vm.hostname = "serverVPN"
  config.vm.provider "virtualbox" do |v|
    v.name = "serverVPN"
    v.memory = "2048"
  end
  config.vm.synced_folder "../../vm.war", "/home/vagrant/link_folder"
  config.vm.provision "ansible_local" do |ansible|
    ansible.playbook = "playbook.yml"
  end
end
